import test from 'node:test';
import assert from 'node:assert/strict';
import {joinFamily,startFamilyRound,roundStartMs} from '../public/room.mjs';
function mock(existing, family=true){const writes=[];const api={doc:(db,...path)=>path.join('/'),serverTimestamp:()=> 'server-time',runTransaction:async(db,fn)=>fn({get:async ref=>ref.includes('/members/')?{exists:()=>!!existing,data:()=>existing}:{exists:()=>family},set:(ref,data)=>writes.push({ref,data})})};return {api,writes};}
test('첫 참여는 본인 참가자 문서만 생성',async()=>{const {api,writes}=mock(null);assert.equal(await joinFamily({api,db:{},uid:'u',code:'ABCDEFGH',name:'수아'}),'수아');assert.deepEqual(writes,[{ref:'rooms/ABCDEFGH/members/u',data:{name:'수아',joinedAt:'server-time'}}]);});
test('재접속은 기존 별명을 복구하고 저장하지 않음',async()=>{const {api,writes}=mock({name:'아빠',joinedAt:'original'});assert.equal(await joinFamily({api,db:{},uid:'u',code:'ABCDEFGH',name:'새 이름'}),'아빠');assert.equal(writes.length,0);});
test('없는 가족방에는 참가자 문서를 생성하지 않음',async()=>{const {api,writes}=mock(null,false);await assert.rejects(joinFamily({api,db:{},uid:'u',code:'ABCDEFGH',name:'수아'}),/가족방이 없어요/);assert.equal(writes.length,0);});
test('시작 시각과 생성 시각을 서버 타임스탬프로 같은 배치에 저장',async()=>{const writes=[];let commits=0;const marker={server:true};const api={doc:(...args)=>args.length===1?{id:'new-round'}:{id:args.at(-1),path:args.slice(1).join('/')},collection:(db,...p)=>p.join('/'),getDocFromServer:async()=>({exists:()=>true,data:()=>({owner:'host'})}),getDocsFromServer:async()=>({docs:[{id:'host'},{id:'guest'}]}),serverTimestamp:()=>marker,writeBatch:()=>({set:(ref,data)=>writes.push({ref,data}),update:(ref,data)=>writes.push({ref,data}),commit:async()=>{commits++;}})};assert.equal(await startFamilyRound({api,db:{},uid:'host',code:'ABCDEFGH',targetMs:5100}),'new-round');assert.equal(writes[0].data.startAt,marker);assert.equal(writes[0].data.createdAt,marker);assert.equal(writes[0].data.countdownMs,5000);assert.deepEqual(writes[0].data.participants,['host','guest']);assert.equal(writes[1].data.currentRound,'new-round');assert.equal(commits,1);});
test('서버 생성 시각 + 5초 및 기존 라운드 시각 호환',()=>{assert.equal(roundStartMs({startAt:{toMillis:()=>10000},countdownMs:5000}),15000);assert.equal(roundStartMs({startAt:{toMillis:()=>10000}}),10000);});
test('다른 참가자는 GO 시작 불가',async()=>{const api={doc:()=>({}),getDocFromServer:async()=>({exists:()=>true,data:()=>({owner:'host'})})};await assert.rejects(startFamilyRound({api,db:{},uid:'guest',code:'ABCDEFGH',targetMs:1000}),/방장만/);});
